import React from 'react';

interface ReportHeaderProps {
  title: string;
  user: string;
  time: string;
  logoUrl?: string;
}

const ReportHeader: React.FC<ReportHeaderProps> = ({ title, user, time, logoUrl }) => (
  <div className="flex items-center justify-between border-b pb-4 mb-6">
    <div className="flex items-center gap-4">
      {logoUrl && (
        <img src={logoUrl} alt="Company Logo" className="h-12 w-auto" />
      )}
      <div>
        <h2 className="text-2xl font-bold">{title}</h2>
        <div className="text-sm text-gray-500">Generated by: <span className="font-semibold">{user}</span></div>
        <div className="text-xs text-gray-400">{time}</div>
      </div>
    </div>
  </div>
);

export default ReportHeader;
