import React, { useState, useEffect } from "react";
import {
  Edit,
  Trash2,
  Search,
  Download,
  CheckSquare,
  Square,
  X,
  FileText,
  UserPlus,
  Users,
  User,
  Car,
  Shield,
  Bell,
} from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import { useSettings } from "@/contexts/SettingContxt";
import { useAuth } from "@/contexts/AuthContext";
import { apiClient } from '@/services/apiClient';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import logo from '@/assets/logo.png'; // Import your logo



interface User {
  id: number;
  email: string;
  first_name: string;
  last_name: string;
  phone: string;
  role: string;
  created_at: string;
  last_login?: string;
}

interface UserStats {
  total: number;
  admin: number;
  owner: number;
  customer: number;
}

interface NewUser {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  phone: string;
  role: string;
}

const UserManagementPage: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { settings, formatPrice, t } = useSettings();
  const { user } = useAuth(); // Get current user info

  // Load user profile from localStorage
  const storedUser = localStorage.getItem('autofleet_user');
  const userProfile = storedUser ? JSON.parse(storedUser) : null;

  // State management
  const [users, setUsers] = useState<User[]>([]);
  const [userStats, setUserStats] = useState<UserStats>({
    total: 0,
    admin: 0,
    owner: 0,
    customer: 0
  });
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [roleFilter, setRoleFilter] = useState("");
  const [selectedUsers, setSelectedUsers] = useState<number[]>([]);
  const [bulkActionLoading, setBulkActionLoading] = useState(false);
  const [exportLoading, setExportLoading] = useState(false);
  const [pdfExportLoading, setPdfExportLoading] = useState(false);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [createLoading, setCreateLoading] = useState(false);
  const [newUser, setNewUser] = useState<NewUser>({
    email: "",
    password: "",
    first_name: "",
    last_name: "",
    phone: "",
    role: "customer"
  });

  // PDF Export Function with logo and current user
  const handlePDFExport = async () => {
    try {
      setPdfExportLoading(true);

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const currentDate = new Date();

      // Use userProfile from localStorage for attribution
      const currentUserName = userProfile ? `${userProfile.first_name} ${userProfile.last_name}` : 'Admin User';
      const currentUserEmail = userProfile?.email || 'admin@example.com';

      // Header with company branding
      doc.setFillColor(44, 62, 125);
      doc.rect(0, 0, pageWidth, 35, 'F');

      // Add logo image
      try {
        doc.addImage(logo, 'PNG', 20, 8, 20, 20); // x, y, width, height
      } catch (error) {
        console.warn('Logo not loaded, using text instead');
        // Fallback to text logo
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(255, 255, 255);
        doc.text('🚗 AutoFleet Hub', 20, 18);
      }

      // Company name next to logo
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text('AutoFleet Hub', 45, 18);

      // Report title on the right
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text('User Management Report', pageWidth - 20, 18, { align: 'right' });

      // Subtitle
      doc.setFontSize(10);
      doc.text('Professional Fleet Management System', pageWidth - 20, 26, { align: 'right' });

      // Report Information Section
      let yPos = 50;
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Report Information', 20, yPos);

      // Report details in two columns
      yPos += 8;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      const reportInfo = [
        ['Report Type:', 'User Management Report'],
        ['Generated By:', currentUserName],
        ['User Email:', currentUserEmail],
        ['Export Date:', currentDate.toLocaleDateString()],
        ['Export Time:', currentDate.toLocaleTimeString()],
        ['Total Records:', users.length.toString()],
        ['Applied Filter:', roleFilter || 'All Roles'],
        ['Search Query:', searchQuery || 'None']
      ];

      // Left column
      reportInfo.slice(0, 4).forEach(([label, value], index) => {
        doc.setFont('helvetica', 'bold');
        doc.text(label, 20, yPos + (index * 6));
        doc.setFont('helvetica', 'normal');
        doc.text(value, 70, yPos + (index * 6));
      });

      // Right column
      reportInfo.slice(4).forEach(([label, value], index) => {
        doc.setFont('helvetica', 'bold');
        doc.text(label, 120, yPos + (index * 6));
        doc.setFont('helvetica', 'normal');
        doc.text(value, 170, yPos + (index * 6));
      });

      // Statistics Summary
      yPos += 35;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Statistics Summary', 20, yPos);

      yPos += 10;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      const statsText = `Total: ${userStats.total} | Customers: ${userStats.customer} | Owners: ${userStats.owner} | Admins: ${userStats.admin}`;
      doc.text(statsText, 20, yPos);

      // Table section
      yPos += 15;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('User Details', 20, yPos);

      // Table data
      const tableColumns = ['#', 'Name', 'Email', 'Phone', 'Role', 'Created'];
      const tableRows = users.map((user, index) => [
        (index + 1).toString(),
        `${user.first_name} ${user.last_name}`,
        user.email,
        user.phone || 'N/A',
        user.role.charAt(0).toUpperCase() + user.role.slice(1),
        new Date(user.created_at).toLocaleDateString()
      ]);

      // Generate table
      autoTable(doc, {
        startY: yPos + 5,
        head: [tableColumns],
        body: tableRows,
        styles: {
          fontSize: 7,
          cellPadding: 2,
          lineColor: [200, 200, 200],
          lineWidth: 0.1
        },
        headStyles: {
          fillColor: [44, 62, 125],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 8
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]
        },
        columnStyles: {
          0: { cellWidth: 15, halign: 'center' },
          1: { cellWidth: 35 },
          2: { cellWidth: 45 },
          3: { cellWidth: 25 },
          4: { cellWidth: 20, halign: 'center' },
          5: { cellWidth: 20, halign: 'center' },
          6: { cellWidth: 25, halign: 'center' }
        },
        didDrawCell: function (data: any) {
          if (data.column.index === 5 && data.cell.section === 'body') {
            const isActive = data.cell.text[0] === 'Active';
            if (isActive) {
              doc.setFillColor(34, 197, 94);
              doc.setTextColor(255, 255, 255);
            } else {
              doc.setFillColor(239, 68, 68);
              doc.setTextColor(255, 255, 255);
            }
          }

          if (data.column.index === 4 && data.cell.section === 'body') {
            const role = data.cell.text[0].toLowerCase();
            if (role === 'admin') {
              doc.setFillColor(147, 51, 234);
            } else if (role === 'owner') {
              doc.setFillColor(59, 130, 246);
            } else {
              doc.setFillColor(34, 197, 94);
            }
            doc.setTextColor(255, 255, 255);
          }
        }
      });

      // Footer
      const pageCount = (doc as any).getNumberOfPages
        ? (doc as any).getNumberOfPages()
        : (doc.internal && typeof (doc.internal as any).getNumberOfPages === 'function'
          ? (doc.internal as any).getNumberOfPages()
          : 1);
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        doc.setFillColor(44, 62, 125);
        doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');

        doc.text('AutoFleet Hub - Fleet Management System', 20, pageHeight - 12);
        doc.text('Confidential Report - Internal Use Only', 20, pageHeight - 6);

        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
        doc.text(`Exported by: ${currentUserName}`, pageWidth - 20, pageHeight - 6, { align: 'right' });
      }

      // Save PDF
      const fileName = `AutoFleet_UserReport_${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(currentDate.getDate()).padStart(2, '0')}_${String(currentDate.getHours()).padStart(2, '0')}${String(currentDate.getMinutes()).padStart(2, '0')}.pdf`;
      doc.save(fileName);

      console.log('PDF report generated successfully');
      alert('PDF report exported successfully!');

    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF report. Please try again.');
    } finally {
      setPdfExportLoading(false);
    }
  };

  // Fetch users with filters
  const fetchUsers = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        page: currentPage.toString(),
        limit: "50",
        ...(searchQuery && { search: searchQuery }),
        ...(roleFilter && { role: roleFilter }),
      });

      console.log('Fetching users with params:', params.toString());
      const response = await apiClient.get(`/users/admin/all?${params}`);
      console.log('Users API Response:', response);

      if (response.success && response.data) {
        let usersData = [];

        if (Array.isArray(response.data)) {
          usersData = response.data;
          setTotalPages(Math.ceil(response.data.length / 50));
        } else if (
          typeof response.data === 'object' &&
          response.data !== null &&
          'users' in response.data &&
          Array.isArray((response.data as any).users)
        ) {
          usersData = (response.data as any).users;
          setTotalPages((response.data as any).pagination?.totalPages || 1);
        } else if (
          typeof response.data === 'object' &&
          response.data !== null &&
          'data' in response.data &&
          Array.isArray((response.data as any).data)
        ) {
          usersData = (response.data as any).data;
          setTotalPages((response.data as any).pagination?.totalPages || 1);
        }

        console.log('Users data:', usersData);
        setUsers(usersData);

        setTimeout(() => {
          if (userStats.total === 0 && usersData.length > 0) {
            console.log('Stats are 0 but we have users, calculating stats...');
            interface StatsAccumulator {
              total: number;
              admin: number;
              owner: number;
              customer: number;
              active: number;
              inactive: number;
            }

            interface StatsUser {
              role: string;
              is_active: boolean;
            }

            const stats = usersData.reduce((acc: StatsAccumulator, user: StatsUser) => {
              acc.total++;
              if (user.role === 'admin') acc.admin++;
              else if (user.role === 'owner') acc.owner++;
              else if (user.role === 'customer') acc.customer++;

              return acc;
            }, {
              total: 0,
              admin: 0,
              owner: 0,
              customer: 0
            });

            console.log('Calculated stats from users data:', stats);
            setUserStats(stats);
          }
        }, 1000);
      }
    } catch (error) {
      console.error('Error fetching users:', error);
      setUsers([]);
    } finally {
      setLoading(false);
    }
  };

  // Fetch user stats - Updated with better handling
  const fetchUserStats = async () => {
    try {
      const response = await apiClient.get('/users/admin/stats/roles');
      console.log('User stats API response:', response);

      if (response.success && response.data) {
        // Handle different response structures
        let statsData = response.data as Partial<UserStats> ?? {};

        // If the response has a nested data property
        if (
          typeof response.data === 'object' &&
          response.data !== null &&
          'data' in response.data
        ) {
          statsData = ((response.data as any).data as Partial<UserStats>) ?? {};
        }

        console.log('Stats data:', statsData);

        setUserStats({
          total: statsData.total ?? 0,
          admin: statsData.admin ?? 0,
          owner: statsData.owner ?? 0,
          customer: statsData.customer ?? 0,
          active: statsData.active ?? 0,
          inactive: statsData.inactive ?? 0,
        });
      } else {
        // Fallback: calculate stats from users data if stats API fails
        console.warn('Stats API failed, calculating from users data');
        calculateStatsFromUsers();
      }
    } catch (error) {
      console.error('Error fetching user stats:', error);
      // Fallback: calculate stats from users data
      calculateStatsFromUsers();
    }
  };

  // Calculate stats from users data as fallback
  const calculateStatsFromUsers = () => {
    if (users.length > 0) {
      const stats = users.reduce((acc, user) => {
        acc.total++;
        if (user.role === 'admin') acc.admin++;
        else if (user.role === 'owner') acc.owner++;
        else if (user.role === 'customer') acc.customer++;

        if (user.is_active) acc.active++;
        else acc.inactive++;

        return acc;
      }, {
        total: 0,
        admin: 0,
        owner: 0,
        customer: 0,
        active: 0,
        inactive: 0
      });

      console.log('Calculated stats from users:', stats);
      setUserStats(stats);
    }
  };

  // Create new user
  const handleCreateUser = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setCreateLoading(true);
      const response = await apiClient.post('/users/admin/create', newUser);

      if (response.success) {
        alert('User created successfully');
        setShowCreateModal(false);
        setNewUser({
          email: "",
          password: "",
          first_name: "",
          last_name: "",
          phone: "",
          role: "customer"
        });
        await fetchUsers();
        await fetchUserStats();
      } else {
        alert('Failed to create user: ' + (response.message || 'Unknown error'));
      }
    } catch (error) {
      console.error('Error creating user:', error);
      alert('Error creating user');
    } finally {
      setCreateLoading(false);
    }
  };

  // Handle bulk role update
  const handleBulkRoleUpdate = async (newRole: string) => {
    if (selectedUsers.length === 0) {
      alert('Please select users to update');
      return;
    }

    try {
      setBulkActionLoading(true);
      const response = await apiClient.put('/users/admin/bulk-update', {
        userIds: selectedUsers,
        action: "role",
        value: newRole
      });

      if (response.success) {
        await fetchUsers();
        await fetchUserStats();
        setSelectedUsers([]);
        alert('Users updated successfully');
      } else {
        alert('Failed to update users');
      }
    } catch (error) {
      console.error('Error updating users:', error);
      alert('Error updating users');
    } finally {
      setBulkActionLoading(false);
    }
  };

  // Export CSV
  const handleExport = async () => {
    try {
      setExportLoading(true);
      const params = new URLSearchParams({
        format: 'csv',
        ...(roleFilter && { role: roleFilter }),
      });

      const response = await fetch(`/api/users/admin/export?${params}`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('autofleet_token')}`,
        },
      });

      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `users_export_${new Date().toISOString().split('T')[0]}.csv`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      } else {
        alert('Export failed');
      }
    } catch (error) {
      console.error('Error exporting data:', error);
      alert('Export failed');
    } finally {
      setExportLoading(false);
    }
  };

  // Toggle user selection
  const toggleUserSelection = (userId: number) => {
    setSelectedUsers(prev =>
      prev.includes(userId)
        ? prev.filter(id => id !== userId)
        : [...prev, userId]
    );
  };

  // Select all users
  const toggleSelectAll = () => {
    if (selectedUsers.length === users.length) {
      setSelectedUsers([]);
    } else {
      setSelectedUsers(users.map(u => u.id));
    }
  };

  // Load data on component mount and when filters change
  useEffect(() => {
    fetchUsers();
  }, [currentPage, searchQuery, roleFilter]);

  useEffect(() => {
    fetchUserStats();
  }, []);

  // Also fetch stats after users are loaded
  useEffect(() => {
    if (users.length > 0 && userStats.total === 0) {
      // Try to fetch stats again or calculate from users
      setTimeout(() => fetchUserStats(), 500);
    }
  }, [users]);

  // Handle search with debounce
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (currentPage !== 1) {
        setCurrentPage(1);
      } else {
        fetchUsers();
      }
    }, 500);

    return () => clearTimeout(timeoutId);
  }, [searchQuery]);

  if (loading && users.length === 0) {
    return (
      <div className={`flex-1 ${settings.darkMode ? "bg-gray-900 text-white" : "bg-gray-50"}`}>
        <div className="flex items-center justify-center h-64">
          <div className={`text-lg ${settings.darkMode ? "text-white" : "text-gray-900"}`}>
            Loading users...
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={`flex-1 ${settings.darkMode ? 'bg-gray-900 text-white' : 'bg-gray-50'}`}>
      {/* Top search bar */}
      <div className="p-8">
        <div className="flex items-center justify-between mb-6">
          <div className="flex-1 flex items-center">
            <input
              type="text"
              placeholder="Search ..."
              className="px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring w-80 bg-white shadow-sm text-gray-900"
            />
          </div>
          <div className="flex items-center gap-4">
            <button className="bg-white p-2 rounded-full shadow">
              <Bell className="w-5 h-5 text-gray-500" />
            </button>
            <div className="bg-white rounded-lg px-3 py-1 flex items-center gap-2 shadow">
              <span className="text-gray-700">EN</span> <span className="text-gray-400">▼</span>
            </div>
          </div>
        </div>

        {/* User Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-6">
          <div className="bg-white rounded-xl p-6 shadow-lg border border-gray-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 text-sm font-medium">Total Users</p>
                <p className="text-2xl font-bold text-gray-900">{userStats.total}</p>
              </div>
              <Users className="w-10 h-10 text-blue-600" />
            </div>
          </div>

          <div className="bg-white rounded-xl p-6 shadow-lg border border-gray-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 text-sm font-medium">Customers</p>
                <p className="text-2xl font-bold text-gray-900">{userStats.customer}</p>
              </div>
              <User className="w-10 h-10 text-green-600" />
            </div>
          </div>

          <div className="bg-white rounded-xl p-6 shadow-lg border border-gray-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 text-sm font-medium">Owners</p>
                <p className="text-2xl font-bold text-gray-900">{userStats.owner}</p>
              </div>
              <Car className="w-10 h-10 text-purple-600" />
            </div>
          </div>

          <div className="bg-white rounded-xl p-6 shadow-lg border border-gray-200">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-600 text-sm font-medium">Active Users</p>
                <p className="text-2xl font-bold text-gray-900">{userStats.active}</p>
              </div>
              <Shield className="w-10 h-10 text-orange-600" />
            </div>
          </div>
        </div>

        {/* User Management Title and Actions */}
        <div className="flex items-center justify-between mb-4">
          <div className="font-semibold text-lg text-gray-700">User Management</div>
          <div className="flex items-center gap-3">
            <button className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-5 py-2 rounded-lg font-semibold shadow disabled:opacity-50">
              <Download className="w-5 h-5" />
              {exportLoading ? 'Exporting...' : 'Export CSV'}
            </button>
            <button
              onClick={handlePDFExport}
              disabled={pdfExportLoading}
              className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg font-semibold shadow disabled:opacity-50"
            >
              <FileText className="w-5 h-5" />
              {pdfExportLoading ? 'Generating...' : 'Export PDF'}
            </button>
            <button
              onClick={() => setShowCreateModal(true)}
              className="flex items-center gap-2 bg-[#1746a2] hover:bg-[#12367a] text-white px-5 py-2 rounded-lg font-semibold shadow"
            >
              <UserPlus className="w-5 h-5" /> Add New User
            </button>
          </div>
        </div>

        {/* Search and Filter */}
        <div className="flex flex-wrap items-center gap-4 mb-4">
          <div className="flex items-center border-2 border-gray-300 rounded-lg px-4 py-3 bg-white w-80 shadow-sm">
            <Search className="w-5 h-5 text-gray-600 mr-3" />
            <input
              type="text"
              placeholder="Search User By name"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-transparent outline-none text-sm w-full text-gray-900 placeholder-gray-600 font-medium"
            />
          </div>
          <select
            value={roleFilter}
            onChange={(e) => setRoleFilter(e.target.value)}
            className="border-2 border-gray-300 rounded-lg px-4 py-3 text-sm bg-white text-gray-900 shadow-sm min-w-[160px] font-medium"
          >
            <option value="" className="text-gray-900 font-medium">All Roles</option>
            <option value="admin" className="text-gray-900 font-medium">Admin</option>
            <option value="owner" className="text-gray-900 font-medium">Owner</option>
            <option value="customer" className="text-gray-900 font-medium">Customer</option>
          </select>

          {/* Bulk Actions */}
          {selectedUsers.length > 0 && (
            <div className="flex items-center gap-3">
              <select
                onChange={(e) => e.target.value && handleBulkRoleUpdate(e.target.value)}
                className="border-2 border-gray-300 rounded-lg px-4 py-3 text-sm bg-white text-gray-900 shadow-sm font-medium"
                disabled={bulkActionLoading}
              >
                <option value="" className="text-gray-900 font-medium">Change Role</option>
                <option value="admin" className="text-gray-900 font-medium">Make Admin</option>
                <option value="owner" className="text-gray-900 font-medium">Make Owner</option>
                <option value="customer" className="text-gray-900 font-medium">Make Customer</option>
              </select>
              <span className="text-sm text-gray-700 font-semibold bg-blue-100 px-3 py-2 rounded-lg">
                {selectedUsers.length} selected
              </span>
            </div>
          )}
        </div>

        {/* Users Table */}
        <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full">
              <thead className="bg-gray-50 border-b-2 border-gray-200">
                <tr>
                  <th className="px-6 py-4 text-left">
                    <button onClick={toggleSelectAll} className="hover:bg-gray-100 p-1 rounded">
                      {selectedUsers.length === users.length && users.length > 0 ? (
                        <CheckSquare className="w-5 h-5 text-blue-600" />
                      ) : (
                        <Square className="w-5 h-5 text-gray-400" />
                      )}
                    </button>
                  </th>
                  <th className="px-6 py-4 text-left font-bold text-gray-800 text-sm uppercase tracking-wider">Name</th>
                  <th className="px-6 py-4 text-left font-bold text-gray-800 text-sm uppercase tracking-wider">Email</th>
                  <th className="px-6 py-4 text-left font-bold text-gray-800 text-sm uppercase tracking-wider">Phone</th>
                  <th className="px-6 py-4 text-left font-bold text-gray-800 text-sm uppercase tracking-wider">Role</th>
                  <th className="px-6 py-4 text-left font-bold text-gray-800 text-sm uppercase tracking-wider">Action</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {loading ? (
                  <tr>
                    <td colSpan={6} className="text-center py-12">
                      <div className="text-gray-500 text-lg font-medium">Loading users...</div>
                    </td>
                  </tr>
                ) : users.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="text-center py-12">
                      <div className="text-gray-500 text-lg font-medium">No users found</div>
                    </td>
                  </tr>
                ) : (
                  users.map((user) => (
                    <tr key={user.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4">
                        <button
                          onClick={() => toggleUserSelection(user.id)}
                          className="hover:bg-gray-100 p-1 rounded"
                        >
                          {selectedUsers.includes(user.id) ? (
                            <CheckSquare className="w-5 h-5 text-blue-600" />
                          ) : (
                            <Square className="w-5 h-5 text-gray-400" />
                          )}
                        </button>
                      </td>
                      <td className="px-6 py-4">
                        <div className="font-bold text-gray-900 text-base">
                          {user.first_name} {user.last_name}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <a
                          href={`mailto:${user.email}`}
                          className="text-blue-700 underline font-medium hover:text-blue-800"
                        >
                          {user.email}
                        </a>
                      </td>
                      <td className="px-6 py-4">
                        <div className="font-medium text-gray-900">{user.phone}</div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`px-3 py-1 rounded-full text-sm font-bold capitalize ${user.role === 'admin' ? 'bg-purple-100 text-purple-700' :
                            user.role === 'owner' ? 'bg-blue-100 text-blue-700' :
                              'bg-green-100 text-green-700'
                          }`}>
                          {user.role}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex gap-2">
                          <button
                            onClick={() => navigate(`/admin/users/${user.id}`)}
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 p-3 rounded-lg transition-colors"
                            title="Edit user"
                          >
                            <Edit className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => {
                              if (confirm('Are you sure you want to delete this user?')) {
                                // Handle delete user
                              }
                            }}
                            className="bg-red-100 hover:bg-red-200 text-red-700 p-3 rounded-lg transition-colors"
                            title="Delete user"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2 px-6 py-4 bg-gray-50 border-t">
              <button
                onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                disabled={currentPage === 1}
                className="px-4 py-2 rounded-lg bg-white border-2 border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 font-medium"
              >
                Previous
              </button>
              {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => (
                <button
                  key={page}
                  onClick={() => setCurrentPage(page)}
                  className={`px-4 py-2 rounded-lg font-bold ${currentPage === page
                      ? 'bg-blue-600 text-white border-2 border-blue-600'
                      : 'bg-white text-gray-700 border-2 border-gray-300 hover:bg-gray-50'
                    }`}
                >
                  {page}
                </button>
              ))}
              <button
                onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                disabled={currentPage === totalPages}
                className="px-4 py-2 rounded-lg bg-white border-2 border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50 font-medium"
              >
                Next
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Create User Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-8 w-96 max-w-90vw">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900">Add New User</h2>
              <button
                onClick={() => setShowCreateModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <form onSubmit={handleCreateUser} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">First Name</label>
                  <input
                    type="text"
                    required
                    value={newUser.first_name}
                    onChange={(e) => setNewUser(prev => ({ ...prev, first_name: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
                  <input
                    type="text"
                    required
                    value={newUser.last_name}
                    onChange={(e) => setNewUser(prev => ({ ...prev, last_name: e.target.value }))}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <input
                  type="email"
                  required
                  value={newUser.email}
                  onChange={(e) => setNewUser(prev => ({ ...prev, email: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                <input
                  type="tel"
                  required
                  value={newUser.phone}
                  onChange={(e) => setNewUser(prev => ({ ...prev, phone: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                <input
                  type="password"
                  required
                  value={newUser.password}
                  onChange={(e) => setNewUser(prev => ({ ...prev, password: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Role</label>
                <select
                  value={newUser.role}
                  onChange={(e) => setNewUser(prev => ({ ...prev, role: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                >
                  <option value="customer">Customer</option>
                  <option value="owner">Owner</option>
                  <option value="admin">Admin</option>
                </select>
              </div>

              <div className="flex gap-3 pt-4">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={createLoading}
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium disabled:opacity-50"
                >
                  {createLoading ? 'Creating...' : 'Create User'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default UserManagementPage;